"""Regenerate docs/analysis-data/analysis.json: the "Results brief" page's
incident-level view of docs/raster-data - see v2_brief.md for the full
design. The raster answers "what happened where?"; this answers "what
deserves attention now, and why?"

Built entirely from docs/raster-data/{manifest,matrix}.json and
docs/raster-data/runs/<run_id>/detail.json (already generated by
anvil_generate_raster_data.py, which must run first) - no new source data.

Core idea: cluster individual failing/erroring test cases into "incidents"
by a normalized signature (the terminal line of a traceback, or the
sharpest available problem message, with volatile substrings like /tmp
paths and encoded IDs scrubbed out - see normalize_signature()). The same
underlying bug then reads as one incident affecting N tools, instead of N
unrelated-looking rows.

An incident's lifecycle state (new/continuing/recovered) is computed per
tool, walking each tool's own attempted-run history exactly like
raster.html's previousAttemptedCell() does - skipping runs where that tool
simply wasn't sampled, so a gap in coverage is never confused with a
recovery. The per-run history strip is coarser (any tool showing the
signature counts as "present" that run) since it's meant as a quick visual,
not a precise state machine.

Usage: anvil_generate_analysis_data.py
"""

import hashlib
import json
import os
import re

import yaml

RASTER_DATA_DIR = "docs/raster-data"
MANIFEST_PATH = f"{RASTER_DATA_DIR}/manifest.json"
MATRIX_PATH = f"{RASTER_DATA_DIR}/matrix.json"
RUNS_DIR = f"{RASTER_DATA_DIR}/runs"
ANALYSIS_DATA_DIR = "docs/analysis-data"
ANALYSIS_PATH = f"{ANALYSIS_DATA_DIR}/analysis.json"
RULES_PATH = os.path.join(os.path.dirname(__file__), "incident_rules.yaml")

HISTORY_LEN = 7  # runs shown in the compact history strip
SHARED_TOOL_THRESHOLD = 2  # >=N distinct tools -> "shared", else tool-specific
PERSISTENT_STREAK_THRESHOLD = 2  # >=N consecutive attempted occurrences -> "persistent"

BAD_STATUSES = {"error", "failure"}

TMP_PATH_RE = re.compile(r"/tmp/tmp[A-Za-z0-9_]+")
UUID_RE = re.compile(r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b", re.IGNORECASE)
HEX_ID_RE = re.compile(r"\b[0-9a-f]{16,}\b", re.IGNORECASE)
JOB_ERROR_RE = re.compile(r"^(Exception: )?Job in error state")


def load_rules() -> list[dict]:
    with open(RULES_PATH) as f:
        rules = yaml.safe_load(f) or []
    for r in rules:
        r["_compiled"] = re.compile(r["pattern"])
    return rules


def classify(signature_text: str, rules: list[dict]) -> tuple[str, str, str | None]:
    for r in rules:
        if r["_compiled"].search(signature_text):
            return r["category"], r["confidence"], r.get("title")
    return "Unknown", "Unclassified", None


def normalize_signature(text: str) -> str:
    text = TMP_PATH_RE.sub("/tmp/<tmp>", text)
    text = UUID_RE.sub("<uuid>", text)
    text = HEX_ID_RE.sub("<id>", text)
    return text.strip()


def extract_signature(execution_problem: str | None, output_problems: list[str] | None) -> str | None:
    """One representative, normalizable line for this test case. Prioritizes
    the execution-level problem (a traceback's final line, or a one-line
    exception like a job-in-error-state message) over downstream
    output-comparison noise Planemo tacks on after a job that never really
    ran - per v2_brief.md: "Do not group every 'Job in error state'
    together. That is only a wrapper; the useful signature is usually
    deeper in stderr or the traceback" - and conversely, a job-in-error
    wrapper that IS the deepest available signal (no traceback at all)
    should win over an incidental diff message that happens to be listed
    after it.
    """
    if execution_problem and execution_problem.strip():
        lines = [ln for ln in execution_problem.strip().splitlines() if ln.strip()]
        if lines:
            return normalize_signature(lines[-1])
    if output_problems:
        for p in output_problems:
            if p and JOB_ERROR_RE.match(p.strip()):
                return normalize_signature(p.strip().splitlines()[0])
        first = next((p for p in output_problems if p and p.strip()), None)
        if first:
            return normalize_signature(first.strip().splitlines()[0])
    return None


def signature_id(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]


def load_json(path: str):
    with open(path) as f:
        return json.load(f)


def short_name(tool_id: str) -> str:
    return tool_id.rsplit("/", 1)[-1]


def build_run_occurrences(run_id: str) -> dict:
    """sig_id -> {text, category, confidence, title, tools: {tool_id: {
    versions: set, tests: int}}, sample: {tool_id, version, raw}} for one
    run's detail.json. Returns {} if that run has no detail.json (shouldn't
    happen for anything in matrix.json's runs list, but tolerate it)."""
    detail_path = os.path.join(RUNS_DIR, run_id, "detail.json")
    if not os.path.exists(detail_path):
        return {}
    detail = load_json(detail_path)

    occurrences: dict[str, dict] = {}
    for tool_id, versions in detail.items():
        for version, tests in versions.items():
            for t in tests:
                if t.get("status") not in BAD_STATUSES:
                    continue
                sig_text = extract_signature(t.get("execution_problem"), t.get("output_problems"))
                if not sig_text:
                    sig_text = "(no problem text captured)"
                sid = signature_id(sig_text)
                entry = occurrences.setdefault(
                    sid,
                    {
                        "text": sig_text,
                        "tools": {},
                        "sample": {
                            "tool_id": tool_id,
                            "version": version,
                            "raw": (t.get("execution_problem") or "\n".join(t.get("output_problems") or []))[:2000],
                            "status": t["status"],
                        },
                    },
                )
                tool_entry = entry["tools"].setdefault(tool_id, {"versions": set(), "tests": 0})
                tool_entry["versions"].add(version)
                tool_entry["tests"] += 1
    return occurrences


def previous_attempted_run(tool_id: str, run_idx: int, runs: list[str], cells: dict) -> str | None:
    """Nearest earlier run (by chronological index) where tool_id was
    actually attempted - mirrors raster.html's previousAttemptedCell()."""
    tool_cells = cells.get(tool_id, {})
    for i in range(run_idx - 1, -1, -1):
        if runs[i] in tool_cells:
            return runs[i]
    return None


def main() -> None:
    manifest = load_json(MANIFEST_PATH)
    matrix = load_json(MATRIX_PATH)
    runs: list[str] = matrix["runs"]
    cells: dict = matrix["cells"]
    manifest_by_run = {m["run_id"]: m for m in manifest}
    rules = load_rules()

    # Pass 1: per-run signature occurrences, and a tool's set of active
    # signatures per run (for the per-tool history walk in pass 2).
    run_occurrences = {run_id: build_run_occurrences(run_id) for run_id in runs}
    tool_sig_by_run: dict[str, dict[str, set]] = {}
    for run_id, occ in run_occurrences.items():
        for sid, entry in occ.items():
            for tool_id in entry["tools"]:
                tool_sig_by_run.setdefault(tool_id, {}).setdefault(run_id, set()).add(sid)

    # Pass 2: global signature registry - first-seen run, and which runs
    # (of the last HISTORY_LEN) it appeared in at all, for the strip.
    all_sig_ids = {sid for occ in run_occurrences.values() for sid in occ}
    sig_text = {}
    sig_first_run_idx = {}
    for idx, run_id in enumerate(runs):
        for sid, entry in run_occurrences[run_id].items():
            sig_text.setdefault(sid, entry["text"])
            if sid not in sig_first_run_idx:
                sig_first_run_idx[sid] = idx
    sig_category = {}
    for sid in all_sig_ids:
        sig_category[sid] = classify(sig_text[sid], rules)

    run_reports = []
    for run_idx, run_id in enumerate(runs):
        occ = run_occurrences[run_id]
        m = manifest_by_run.get(run_id, {})
        tools_attempted_total = m.get("tools_attempted") or 0

        incidents = []
        recovered = []
        active_tools_all = set()
        total_tests_affected = 0

        for sid, entry in occ.items():
            tools = entry["tools"]
            tools_affected = len(tools)
            tests_affected = sum(t["tests"] for t in tools.values())
            versions_affected = sum(len(t["versions"]) for t in tools.values())
            active_tools_all.update(tools)
            total_tests_affected += tests_affected

            # Per-tool new/continuing classification and streak, from each
            # tool's own attempted-run history (not run_idx-1 blindly -
            # that tool may not have been sampled last time).
            per_tool_new = 0
            per_tool_continuing = 0
            max_streak = 1
            for tool_id in tools:
                streak = 1
                cursor_idx = run_idx
                is_new = True
                while True:
                    prev_run = previous_attempted_run(tool_id, cursor_idx, runs, cells)
                    if prev_run is None:
                        break
                    prev_sigs = tool_sig_by_run.get(tool_id, {}).get(prev_run, set())
                    if sid in prev_sigs:
                        is_new = False
                        streak += 1
                        cursor_idx = runs.index(prev_run)
                    else:
                        break
                if is_new:
                    per_tool_new += 1
                else:
                    per_tool_continuing += 1
                max_streak = max(max_streak, streak)

            is_shared = tools_affected >= SHARED_TOOL_THRESHOLD
            if per_tool_continuing > 0:
                state = "Persistent" if max_streak >= PERSISTENT_STREAK_THRESHOLD + 1 else "Continuing"
            else:
                state = "New"

            # Coarse per-run presence strip, most recent HISTORY_LEN runs
            # (oldest first), padded with None for runs before history began.
            history = []
            for i in range(run_idx - HISTORY_LEN + 1, run_idx + 1):
                if i < 0:
                    history.append(None)
                else:
                    history.append(sid in run_occurrences[runs[i]])

            category, confidence, title = sig_category[sid]
            if not title:
                title = entry["text"][:80]

            fraction_of_toolset = tools_affected / tools_attempted_total if tools_attempted_total else 0
            evidence = []
            if is_shared:
                evidence.append(f"{tools_affected} tools")
                if tools_attempted_total:
                    evidence.append(f"{round(fraction_of_toolset * 100)}% of tested toolset")
            else:
                sample_tool = next(iter(tools))
                tool_cell = cells.get(sample_tool, {}).get(run_id, {})
                tool_tests_attempted = tool_cell.get("tests_attempted") or 0
                if tool_tests_attempted:
                    evidence.append(f"{tests_affected} of {tool_tests_attempted} tests affected")
                if versions_affected > 1:
                    evidence.append(f"{versions_affected} versions")
            if max_streak >= 2:
                evidence.append(f"{max_streak} consecutive runs")
            if versions_affected and is_shared:
                evidence.append(f"{versions_affected} versions")

            incidents.append(
                {
                    "id": sid,
                    "title": title,
                    "category": category,
                    "confidence": confidence,
                    "state": state,
                    "shared": is_shared,
                    "tools_affected": tools_affected,
                    "versions_affected": versions_affected,
                    "tests_affected": tests_affected,
                    "streak": max_streak,
                    "fraction_of_toolset": round(fraction_of_toolset, 4),
                    "tools": sorted(tools, key=short_name),
                    "history": history,
                    "evidence": evidence,
                    "sample": entry["sample"],
                    "first_seen_run": runs[sig_first_run_idx[sid]],
                }
            )

        # Recovered: signatures active in this tool's *previous attempted*
        # run but not in this run's attempt (and this run did attempt it -
        # untested means "unknown", not "recovered").
        seen_recovered = set()
        for tool_id, by_run in tool_sig_by_run.items():
            if run_id not in cells.get(tool_id, {}):
                continue  # not attempted this run - can't have recovered
            current_sigs = by_run.get(run_id, set())
            prev_run = previous_attempted_run(tool_id, run_idx, runs, cells)
            if prev_run is None:
                continue
            for sid in by_run.get(prev_run, set()):
                if sid in current_sigs:
                    continue
                key = (tool_id, sid)
                if key in seen_recovered:
                    continue
                seen_recovered.add(key)
                category, confidence, title = sig_category[sid]
                recovered.append(
                    {
                        "id": sid,
                        "title": title or sig_text[sid][:80],
                        "category": category,
                        "tool": tool_id,
                        "recovered_since_run": run_id,
                    }
                )

        shared_incidents = sorted(
            (i for i in incidents if i["shared"]),
            key=lambda i: (-i["tools_affected"], -i["fraction_of_toolset"], -i["streak"], -i["tests_affected"]),
        )
        tool_specific = [i for i in incidents if not i["shared"]]
        persistent_tool_issues = sorted(
            (i for i in tool_specific if i["state"] in ("Continuing", "Persistent")),
            key=lambda i: (-i["streak"], -i["fraction_of_toolset"], -i["versions_affected"]),
        )
        new_isolated_issues = sorted(
            (i for i in tool_specific if i["state"] == "New"),
            key=lambda i: (-i["fraction_of_toolset"], -i["versions_affected"]),
        )

        new_count = sum(1 for i in incidents if i["state"] == "New")
        continuing_count = sum(1 for i in incidents if i["state"] in ("Continuing", "Persistent"))
        recovered_count = len({(r["tool"]) for r in recovered})

        summary_sentence = build_summary_sentence(
            total_tests_affected, len(active_tools_all), shared_incidents, persistent_tool_issues
        )

        run_reports.append(
            {
                "run_id": run_id,
                "timestamp": m.get("timestamp"),
                "results_html_url": m.get("results_html_url"),
                "tools_attempted": tools_attempted_total,
                "summary_sentence": summary_sentence,
                "counts": {"new": new_count, "continuing": continuing_count, "recovered": recovered_count},
                "shared_incidents": shared_incidents,
                "persistent_tool_issues": persistent_tool_issues,
                "new_isolated_issues": new_isolated_issues,
                "recovered": recovered,
            }
        )

    os.makedirs(ANALYSIS_DATA_DIR, exist_ok=True)
    with open(ANALYSIS_PATH, "w") as f:
        json.dump({"runs": run_reports}, f, separators=(",", ":"))

    print(f"Wrote {ANALYSIS_PATH} ({len(run_reports)} runs, {len(all_sig_ids)} distinct signatures)")


def build_summary_sentence(total_tests: int, total_tools: int, shared: list[dict], persistent: list[dict]) -> str:
    if total_tests == 0:
        return "No test failures or errors in this run."
    parts = [f"{total_tests} test{'s' if total_tests != 1 else ''} affected across {total_tools} tool{'s' if total_tools != 1 else ''}."]
    if shared:
        top = shared[0]
        parts.append(
            f"One shared {top['category'].lower()} incident accounts for {top['tests_affected']} "
            f"{'errors' if 'error' in top['sample']['status'] else 'test failures'}."
        )
    if persistent:
        parts.append(
            f"{len(persistent)} tool-specific problem{'s are' if len(persistent) != 1 else ' is'} "
            "continuing from earlier runs."
        )
    return " ".join(parts)


if __name__ == "__main__":
    main()
